Add dev-perl/Module-Build to DEPEND!
Fix this QA error:
Using Module::Build
QA Notice: The ebuild uses Module::Build but doesn't depend on it.
ERROR: dev-perl/IO-CaptureOutput-1.1102::splog-gentoo failed (configure phase):
Add dev-perl/Module-Build to DEPEND!